# Generated by Django 4.0.4 on 2022-04-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogador', '0001_initial'),
        ('golpe', '0001_initial'),
        ('set', '0001_initial'),
        ('quadrante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('acerto', 'Acerto'), ('erro', 'Erro'), ('normal', 'Normal')], default='normal', max_length=6)),
                ('ponto_jogador', models.PositiveIntegerField(default=0)),
                ('ponto_jogador_adversario', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('golpe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golpe.golpe')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogador.jogador')),
                ('quadrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadrante.quadrante')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.set')),
            ],
            options={
                'verbose_name_plural': 'Jogadas',
                'db_table': 'jogada',
                'ordering': ['set'],
            },
        ),
    ]
