# Generated by Django 4.0.4 on 2022-05-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogada', '0002_remove_jogada_ponto_jogador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogada',
            name='acerto',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
