# Generated by Django 4.0.4 on 2022-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('lateralidade', models.CharField(choices=[('destro', 'Destro'), ('canhoto', 'Canhoto'), ('ambidestro', 'Ambidestro'), ('naoinformado', 'Não informado')], default='naoinformado', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Jogadores',
                'db_table': 'jogador',
                'ordering': ['nome_jogador'],
            },
        ),
    ]
