# Generated by Django 4.0.4 on 2022-04-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.PositiveIntegerField(blank=True, null=True)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partida.partida')),
            ],
            options={
                'verbose_name_plural': 'Sets',
                'db_table': 'set',
                'ordering': ['partida', 'ordem'],
            },
        ),
    ]
