# Generated by Django 4.0.4 on 2022-04-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='duracao',
        ),
    ]
