# Generated by Django 4.0.4 on 2022-04-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateTimeField()),
                ('tipo_jogo', models.CharField(choices=[('simples', 'Simples'), ('dupla', 'Dupla')], default='simples', max_length=7)),
                ('modalidade', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('misto', 'Misto')], default='misto', max_length=9)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jogador_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogador_1', to='jogador.jogador')),
                ('jogador_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jogador_2', to='jogador.jogador')),
                ('jogador_adversario_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogador_adversario_1', to='jogador.jogador')),
                ('jogador_adversario_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jogador_adversario_2', to='jogador.jogador')),
            ],
            options={
                'verbose_name_plural': 'Partidas',
                'db_table': 'partida',
                'ordering': ['data_partida'],
            },
        ),
    ]
