# Generated by Django 4.0.4 on 2022-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_quadrante', models.CharField(max_length=100)),
                ('lado', models.CharField(choices=[('esquerdo', 'Esquerdo'), ('direito', 'Direito')], default='esquerdo', max_length=9)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quadrantes',
                'db_table': 'quadrante',
                'ordering': ['descricao_quadrante'],
            },
        ),
    ]
