# Generated by Django 4.0.4 on 2022-06-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadrante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadrante',
            name='lado',
            field=models.CharField(blank=True, choices=[('esquerdo', 'Esquerdo'), ('direito', 'Direito')], max_length=9, null=True),
        ),
    ]
